wip: Add custom encodings
mittwald/kubernetes-secret-generator pull request #29
Opened 2020-11-25 15:39 UTC by YannikBramkamp

2020-11-26 13:58 UTC, martin-helmich requested changes

2020-11-26 13:58 UTC, martin-helmich commented on pkg/controller/secret/secret_controller.go
>  	return l, nil
Shorter:

```suggestion
	if val, ok := annotations[AnnotationSecretEncoding]; ok {
		return l, nil
	}
	return fallback, nil
```

2020-11-26 13:58 UTC, martin-helmich commented on pkg/controller/secret/secret_controller.go
> +	val = strings.ToLower(val)
Please `go fmt` everything. I'm wondering why Codeclimate didn't pick up on this... 🤔

2020-11-26 13:58 UTC, martin-helmich commented on pkg/controller/secret/secret_string.go
> +	length, byteLen, err := secretLengthFromAnnotation(secretLength(), instance.Annotations)
`byteLen` is named a bit ambiguously: From the name `byteLen`, one might believe that this variables contains "the actual desired secret length in bytes" and not "`true` if another variable `length` contains the byte length, else `false`". Maybe name this `isByteLength`?

2020-11-26 13:58 UTC, martin-helmich commented on pkg/controller/secret/secret_string.go
> +func generateRandomString(length int, encoding string, lenBytes bool) (string, error) {
You could make this function also return a `[]byte` (it's converted to `[]byte` later, anyway) and then make this function also handle the raw string generation (which is now done by `generateRandomStringRaw`)

2020-11-26 13:58 UTC, martin-helmich commented on pkg/controller/secret/types.go
> +	AnnotationSecretEncoding        = "secret-generator.v1.mittwald.de/encoding"
Please don't forget to also adjust the `README.md`

2020-11-26 13:58 UTC, martin-helmich commented on pkg/controller/secret/secret_controller.go
> +	byteLen := false
See my other comment on the `byteLen` naming.

2020-11-26 16:39 UTC, martin-helmich approved these changes
LGTM! 👍

2020-11-27 07:47 UTC, merged

2020-12-04 00:50 UTC, stuartpb reviewed
Looks great! I have a qualm with one minor detail, though - see comment inline. I didn't include this in my original spec from #27 because I felt it was rather wordy enough as it was :sweat_smile:

2020-12-04 00:50 UTC, stuartpb commented on README.md
> +The suffix `B` or `b` can be used to indicate that the provided value should refer to the encoded byte sequence instead.
This is the one quibble I was hoping I wouldn't have to bring up by submitting the PR myself: the lower-case suffix `b` should **not** be supported, as `b` is the suffix for **bits**, not bytes, and should technically divide the value by 8 - value of `64b` is equivalent to `8B`. (This is more commonly recognized in forms like "Mbps" for "megabits per second", where the number of mega*bytes* that will be downloaded in a second must be calculating by dividing by eight).