WIP: Add ability to generate secrets from CRs
mittwald/kubernetes-secret-generator pull request #35
Opened 2021-02-15 09:10 UTC by YannikBramkamp

Closes #34

2021-02-17 15:12 UTC, YannikBramkamp commented
Notes:
- Had to move unit tests into a single package, as each controller test requires a manager, but I couldn't find a way to terminate a created manager at the end of a test, leading to "this port is already in use" errors.
- Code climate issues are pretty much all related to receiver functions of the operators

2021-03-29 02:28 UTC, mittwald-machine commented
There has not been any activity to this pull request in the last 30 days. It will automatically be closed after 7 more days. Remove the `stale` label to prevent this.

2021-04-26 05:34 UTC, martin-helmich commented
@YannikBramkamp Thanks for all your work on this! :+1:  I'll happily review this, but since this is a big one, it might take a few days until I get to it... ⏳

2021-05-25 09:16 UTC, martin-helmich requested changes

2021-05-25 09:16 UTC, martin-helmich commented on pkg/apis/types/v1alpha1/deepcopy.go
> +func (in *StringSecret) DeepCopyInto(out *StringSecret) {
Same question as with the CRD YAML files: Are these written manually, or autogenerated? If the former, please replace with the autogenerated versions from Operator-SDK.

2021-05-25 09:16 UTC, martin-helmich commented on pkg/apis/types/v1alpha1/stringsecret.go
> +}
As earlier, please pay attention to which fields are actually optional/`omitempty` and which are required. Optional fields should also recieve an `// +optional` annotation for operator-sdk's code generation.

2021-05-25 09:16 UTC, martin-helmich commented on pkg/controller/crd/basicauth/basicauth_controller.go
> +	values[secret.SecretFieldBasicAuthPassword] = password
I'm seeing a bit of code duplication here. Can we maybe refactor some of the code in `createNewSecret` and `updateSecret` into a common function?

2021-05-25 09:16 UTC, martin-helmich commented on pkg/controller/crd/sshkeypair/sshkeypair_controller.go
> +	}
Also a bit of code duplication with the other controllers. I believe you could solve this generically by using the `metav1.Object` interface, which should be implemented by all CRs that embed the `metav1.ObjectMeta` struct.

2021-05-25 09:16 UTC, martin-helmich commented on pkg/controller/crd/sshkeypair/sshkeypair_controller.go
> +	existingPublicKey, err = secret.SshPublicKeyForPrivateKey(rsaKey)
(Nitpick) Inconsistent naming: `Ssh` vs. `SSH` -- since in Go, abbreviations and protocol names are usually named all-uppercased in function names, this should be named `SSHPublicKeyForPrivateKey`

2021-05-25 09:16 UTC, martin-helmich commented on pkg/controller/crd/stringsecret/stringsecret_controller.go
> +func (r *ReconcileStringSecret) UpdateSecret(ctx context.Context, instance *v1alpha1.StringSecret, existing *v1.Secret) (reconcile.Result, error) {
Why is `createNewSecret` private, and `UpdateSecret` public?

2021-05-25 09:16 UTC, martin-helmich commented on pkg/controller/crd/types.go
> +	err = c.Create(context.Background(), desiredSecret)
```suggestion
	err = c.Create(ctx, desiredSecret)
```

❓

2021-05-25 09:16 UTC, martin-helmich commented on pkg/controller/crd/types.go
> +		return reconcile.Result{Requeue: true}, err
Requeing is (automatically) implied when returning an error, so `Requeue: true` is not strictly necessary (although not hurtful, either).

2021-05-25 09:16 UTC, martin-helmich commented on pkg/controller/secret/secret_basic_auth.go
> +	instance.Data[SecretFieldBasicAuthPassword] = password
I acknowledge this is going to be tough, but now there's quite a bit of code duplication between the different implementations (annotation-based and CR-based). Any chance to extract this (all these) into a common function?

2021-05-25 09:16 UTC, martin-helmich commented on pkg/controller/secret/basicauth_controller_test.go
> +package secret_test
If I see it correctly, there're now two different packages, `secret` and `secret_test` in this directory. TBH I'm surprised this works at all... 😳

2021-05-25 09:17 UTC, martin-helmich commented
>  I'll happily review this, but since this is a big one, it might take a few days until I get to it... ⏳

@YannikBramkamp Finally got around to leaving a few notes on this -- sorry it took so long. 🙄🙏

2021-05-25 12:09 UTC, YannikBramkamp commented on pkg/controller/secret/basicauth_controller_test.go
> +package secret_test
The reason for this is that having the tests in the same package would result in an import cycle, as the test import `opkg/controller/crd`, which in turn imports `pkg/controller/secret`. 
The code works because of an exception to the general rule that one directory can only contain one package for `_test.go` files. From https://golang.org/pkg/cmd/go/internal/test/: `
Test files that declare a package with the suffix "_test" will be compiled as a
separate package, and then linked and run with the main test binary.`

2021-06-28 02:12 UTC, mittwald-machine commented
There has not been any activity to this pull request in the last 30 days. It will automatically be closed after 7 more days. Remove the `stale` label to prevent this.

2021-07-01 12:55 UTC, YannikBramkamp commented on deploy/helm-chart/crds/basicauth-crd.yaml
> +  name: basicauths.mittwald.systems
I now exchanged my manually generated files with operator-sdk generated files

2021-07-01 13:03 UTC, YannikBramkamp commented on pkg/controller/secret/secret_basic_auth.go
> +	instance.Data[SecretFieldBasicAuthPassword] = password
I tried to reduce code duplication where possible, by using functions shared between both approaches for data generation

2021-07-02 07:11 UTC, YannikBramkamp commented
@martin-helmich  This should be ready now, I hope I didn't forget anything, as there was quite a bit of time between when I started to implement the requested changes and when I finished,

2021-08-02 02:09 UTC, mittwald-machine commented
There has not been any activity to this pull request in the last 30 days. It will automatically be closed after 7 more days. Remove the `stale` label to prevent this.

2021-08-30 06:53 UTC, martin-helmich requested changes

2021-08-30 06:53 UTC, martin-helmich commented on pkg/controller/secret/secret_ssh.go
> +	return nil
Typically a matter of style and preference, but an early exit would reduce nesting a bit, in this case:

```suggestion
	if len(publicKey) > 0 {
		return nil
	}
	
	// restore public key if private key exists
	rsaKey, err := PrivateKeyFromPEM(privateKey)
	if err != nil {
		return err
	}

	publicKey, err = SSHPublicKeyForPrivateKey(rsaKey)
	if err != nil {
		return err
	}

	data[SecretFieldPublicKey] = publicKey

	return nil
```

2021-08-30 06:53 UTC, martin-helmich commented on pkg/controller/secret/secret_string.go
> +func (pg StringGenerator) determineKeysToRegenerate(instance *corev1.Secret, genKeys []string) (reconcile.Result, error) {
I find the function name a bit misleading; "determine keys ..." suggests to me that the function actually only _determines_ which keys should be regenerated, but not _actually_ regenerating them. Maybe rename this...

```suggestion
func (pg StringGenerator) regenerateKeysWhereRequired(instance *corev1.Secret, genKeys []string) (reconcile.Result, error) {
```

❓

2021-08-30 06:54 UTC, martin-helmich commented
@YannikBramkamp Sorry for letting this stew for so long... We really need to get @mittwald-machine under control. 😅

2021-08-30 08:26 UTC, YannikBramkamp commented
@martin-helmich I've iImplemented the changes.

2021-08-30 08:51 UTC, martin-helmich approved these changes

2021-08-30 08:51 UTC, merged