Make cluster role optional
mittwald/kubernetes-secret-generator pull request #38
Opened 2021-03-19 02:42 UTC by day1118

Resolves #37

2021-03-19 13:38 UTC, martin-helmich reviewed
:+1: Thanks for the contribution, I think this is a sensible change to make. However, I suspect that the new values (or their effects, rather) might not be inherently obvious to the user, so they might warrant a bit of documentation. What do you think?

2021-03-19 13:38 UTC, martin-helmich commented on deploy/helm-chart/kubernetes-secret-generator/templates/_helpers.tpl
> +{{- end -}}
TBH, it took me a few minutes to follow under which circumstances which exact value is used as watch namespace (and I suspect this might be even more difficult to follow for the unsuspecting user). This might warrant a bit of documentation (maybe just a few comments in the `values.yaml` would already be sufficient).

2021-03-19 20:15 UTC, day1118 commented
That makes sense. Are you happy with the code changes? If so I'll draft something for the readme.

2021-03-19 21:58 UTC, day1118 commented on deploy/helm-chart/kubernetes-secret-generator/templates/_helpers.tpl
> +{{- end -}}
I considered some simpler logic here, but wanted to ensure that the behaviour only occurred in a very specific situation to ensure nothing was impacted for existing users.

2021-03-29 21:38 UTC, day1118 commented
Hi @martin-helmich 
Anything further that you require so that this can be merged?
Thanks

2021-04-22 23:15 UTC, day1118 commented
Can you please provide any feedback/review @martin-helmich 
Thanks

2021-05-17 13:21 UTC, YannikBramkamp requested changes
I marked a few small nitpicks, apart from that this looks good to me

2021-06-18 10:33 UTC, day1118 commented
> I marked a few small nitpicks, apart from that this looks good to me

Thanks @YannikBramkamp - changes have been accepted

2021-06-18 12:17 UTC, martin-helmich approved these changes
Looking good, I think! :+1:  Sorry for the delayed review. 🙄 🙏

2021-06-18 12:17 UTC, martin-helmich commented on deploy/helm-chart/kubernetes-secret-generator/templates/_helpers.tpl
> +{{- end -}}
> but wanted to ensure that the behaviour only occurred in a very specific situation to ensure nothing was impacted for existing users.

I can get that. Breaking backwards compatibility would indeed be an annoyance. :+1:

2021-06-18 12:18 UTC, martin-helmich commented
@YannikBramkamp Looks like the changes you've requested have been implemented. Do you want to have a last look? Otherwise, I'll probably just go ahead and merge this shortly.

2021-06-18 13:12 UTC, YannikBramkamp approved these changes

2021-06-18 13:16 UTC, YannikBramkamp commented
@martin-helmich looks good to me, too

2021-06-18 16:22 UTC, merged