Add correct permissions for monitoring service and make its creation optional
mittwald/kubernetes-secret-generator pull request #42
Opened 2021-04-23 15:08 UTC by YannikBramkamp

Closes #41

2021-05-24 02:42 UTC, mittwald-machine commented
There has not been any activity to this pull request in the last 30 days. It will automatically be closed after 7 more days. Remove the `stale` label to prevent this.

2021-05-25 08:49 UTC, martin-helmich commented
@YannikBramkamp This one is still marked as "Draft" and is getting stale by now. Is this ready for review, or does it still need some ❤️?

2021-05-25 11:31 UTC, YannikBramkamp commented
> @YannikBramkamp This one is still marked as "Draft" and is getting stale by now. Is this ready for review, or does it still need some heart?

@martin-helmich I figured I'd wait for #38 to be merged, since I'll preobably have to make some changes to this pr.

2021-06-25 02:15 UTC, mittwald-machine commented
There has not been any activity to this pull request in the last 30 days. It will automatically be closed after 7 more days. Remove the `stale` label to prevent this.

2021-06-30 14:41 UTC, YannikBramkamp commented
This should be ready now @martin-helmich

2021-07-02 12:57 UTC, hensur requested changes

2021-07-02 12:57 UTC, hensur commented on Makefile
> +	kubectl delete -f deploy/role.yaml -n ${NAMESPACE}
```suggestion
	kubectl apply -f deploy/role_with_service_permissions.yaml -n ${NAMESPACE}
```

2021-07-02 12:57 UTC, hensur commented on README.md
> +- `useMetricsService` toggles whether the operator should provide a service for metrics monitoring by Prometheus. If this is set to true, the operator will start with additional permissions, namely `
"the apiGroup `""`" looks a bit strange, I would probably just call it the `core` apiGroup or completely omit the group.

2021-07-09 07:59 UTC, hensur approved these changes

2021-07-28 05:58 UTC, merged