Adds support for overriding imagepullsecrets and image registry globally
mittwald/kubernetes-secret-generator pull request #48
Opened 2021-07-08 17:38 UTC by ptcar2009

closes #47

2021-07-09 07:58 UTC, hensur requested changes

2021-07-09 07:58 UTC, hensur commented on deploy/helm-chart/kubernetes-secret-generator/templates/_helpers.tpl
> +{{ include "common.images.pullSecrets" ( dict "images" (list .Values.path.to.the.image1, .Values.path.to.the.image2) "global" .Values.global) }}
```suggestion
{{ include "common.images.pullSecrets" ( dict "images" (list .Values.image) "global" .Values.global) }}
```

2021-07-09 07:58 UTC, hensur commented on deploy/helm-chart/kubernetes-secret-generator/templates/_helpers.tpl
> +{{ include "common.images.pullSecrets" ( dict "images" (list .Values.path.to.the.image1, .Values.path.to.the.image2) "global" .Values.global) }}
It's just a comment, but I think it looks cleaner this way :)

2021-07-13 21:28 UTC, ptcar2009 commented on deploy/helm-chart/kubernetes-secret-generator/templates/_helpers.tpl
> +{{ include "common.images.pullSecrets" ( dict "images" (list .Values.path.to.the.image1, .Values.path.to.the.image2) "global" .Values.global) }}
I agree, I got the helpers comment from bitnami's charts

2021-08-12 18:28 UTC, ptcar2009 commented
@hensur can you take a look at it again? it's a pretty simple change and shouldn't really affect anything

2021-08-30 07:08 UTC, martin-helmich approved these changes
Sorry for the delay. 🙄🙏  Thanks for your contribution! :+1:

2021-08-30 07:45 UTC, merged

2021-08-30 20:27 UTC, ptcar2009 commented
@martin-helmich sorry for bothering again, but is there any way to create a new version of the helm chart containing this change?

2021-09-08 12:26 UTC, day1118 commented
> @martin-helmich sorry for bothering again, but is there any way to create a new version of the helm chart containing this change?

Can you please cut a release @martin-helmich @hensur?
Thanks